local basalt = require("basalt") -- we need basalt here
local mainFrame = basalt.createFrame()
local aList = mainFrame:addList()
aList:addItem("1. Entry")
aList:addItem("2. Entry", colors.yellow)
aList:addItem("3. Entry", colors.yellow, colors.green)
aList:onSelect(function (self,event,item)
  basalt.debug(aList:getItemIndex())
end)
basalt.autoUpdate()