local basalt = require(".../DOS.script.basalt")
local main = basalt.createFrame()
basalt.onEvent(function(event, side, channel, replyChannel, message, distance)
        basalt.debug("Message received: ")
end)
basalt.autoUpdate()