local basalt = require(".../DOS.script.basalt")
local cat = require(".../DOS.script.cat")
local mainFrame = basalt.createFrame()
cat.Basalt.Window_Over(mainFrame,"Set up",colors.lightBlue)
basalt.autoUpdate()